ALTER TYPE "MatchStatus" ADD VALUE 'DRAFT' BEFORE 'CONFIGURING';
ALTER TABLE "Match" ADD COLUMN "draftPick" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN "draftTeamA" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Match" ADD COLUMN "draftTeamB" TEXT NOT NULL DEFAULT '[]';
