ALTER TABLE "MatchPlayer" ADD COLUMN "headshots" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayer" ADD COLUMN "damage" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayer" ADD COLUMN "flashAssists" INTEGER NOT NULL DEFAULT 0;
